steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/evershop:$SHORT_SHA', '.']

  # Step 2: Push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/evershop:$SHORT_SHA']

  # Step 3: Tag the image with the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/evershop:$SHORT_SHA', 'gcr.io/$PROJECT_ID/evershop:latest']

  # Step 4: Push the image with the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/evershop:latest']

    
  # Step to replace placeholders in deployment.yaml
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i 's|<PROJECT_ID>|'"$PROJECT_ID"'|g' ./deployment/kubernetes/deployment.yaml
        sed -i 's|<VERSION>|'"$SHORT_SHA"'|g' ./deployment/kubernetes/deployment.yaml
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=europe-west1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=evershop-cluster'

  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'deployment/kubernetes/deployment.yaml']


  

images:
  - 'gcr.io/$PROJECT_ID/evershop:$SHORT_SHA'
