apiVersion: v1
kind: Service
metadata:
  name: evershop-service
spec:
  type: LoadBalancer
  selector:
    app: evershop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
